chain:
    bech32_prefix: deweb
    modules: [bridge_transactions]
bridge:
    address: deweb1rl3wl5v7cln6m3hekp39lfe6244t420mnc540m
    networks:
        sia:
            token: deweb14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s03q9ga
    consensus_host: http://localhost:8083
node:
    type: remote
    config:
        rpc:
            address: http://localhost:26657
            client_name: juno
            max_connections: 20
        grpc:
            address: localhost:9090
            insecure: true
parsing:
    workers: 1
    parse_genesis: true
database:
    name: deweb_juno
    host: localhost
    port: 5432
    user: postgres
    password: pg_secret
    schema: public
    max_open_connections: 1
    max_idle_connections: 1
logging:
    level: info
    format: text
