chain:
    bech32_prefix: deweb
    modules: [tokens_transactions]
node:
    type: remote
    config:
        rpc:
            address: http://localhost:26657
            client_name: juno
            max_connections: 20
        grpc:
            address: localhost:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
database:
    name: juno_db
    host: localhost
    port: 5432
    user: postgres
    password: pg_secret
    schema: public
    max_open_connections: 1
    max_idle_connections: 1
logging:
    level: debug
    format: text
